/*
 * Created on 2019-04-16 ( Date ISO 2019-04-16 - Time 01:28:59 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.Ecommerce.entity;

import java.io.Serializable;


import javax.persistence.*;

/**
 * Persistent class for "Item" entity stored in table "item" <br>
 * This class is a "record entity" without JPA links  <br>
 *
 *
 */
@Entity
@Table(name="item", schema="public" )
// Define named queries here

  @NamedQueries ( {
  
 @NamedQuery ( name="ItemJpaRecord.countAll",
  query="SELECT COUNT(x) FROM ItemJpaRecord x" ),
 
 @NamedQuery ( name="ItemJpaRecord.countById",
  query="SELECT COUNT(x) FROM ItemJpaRecord x WHERE x.itemId = ?1 " ) } )
 
public class ItemJpaRecord implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="item_id", nullable=false)
    private Integer    itemId       ; 

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="item_name", length=2147483647)
    private String     itemName     ; 

    @Column(name="quantity")
    private Integer    quantity     ; 

    @Column(name="allocated")
    private Integer    allocated    ; 


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ItemJpaRecord() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setItemId( Integer itemId ) {
        this.itemId = itemId ;
    }
    public Integer getItemId() {
        return this.itemId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : item_name ( varchar ) 
    public void setItemName( String itemName ) {
        this.itemName = itemName;
    }
    public String getItemName() {
        return this.itemName;
    }

    //--- DATABASE MAPPING : quantity ( int4 ) 
    public void setQuantity( Integer quantity ) {
        this.quantity = quantity;
    }
    public Integer getQuantity() {
        return this.quantity;
    }

    //--- DATABASE MAPPING : allocated ( int4 ) 
    public void setAllocated( Integer allocated ) {
        this.allocated = allocated;
    }
    public Integer getAllocated() {
        return this.allocated;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(itemId);
        sb.append("]:"); 
        sb.append(itemName);
        sb.append("|");
        sb.append(quantity);
        sb.append("|");
        sb.append(allocated);
        return sb.toString(); 
    } 

}
