/*
 * Created on 2019-04-16 ( Date ISO 2019-04-16 - Time 01:28:59 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.Ecommerce.entity;

import java.io.Serializable;

import javax.persistence.*;

/**
 * Persistent class for "Oder" entity stored in table "oder" <br>
 * This class is a "record entity" without JPA links <br>
 *
 *
 */
@Entity
@Table(name = "oder", schema = "public")
// Define named queries here
/*
 * @NamedQueries ( {
 * 
 * @NamedQuery ( name="OderJpaRecord.countAll",
 * query="SELECT COUNT(x) FROM OderJpaRecord x" ),
 * 
 * @NamedQuery ( name="OderJpaRecord.countById",
 * query="SELECT COUNT(x) FROM OderJpaRecord x WHERE x.orderId = ?1 " ) } )
 */
public class OrderJpaRecord implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "order_id", nullable = false)
	private Integer orderId;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	@Column(name = "email_id", length = 2147483647)
	private String emailId;

	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public OrderJpaRecord() {
		super();
	}

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : email_id ( varchar )
	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public String getEmailId() {
		return this.emailId;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("[");
		sb.append(orderId);
		sb.append("]:");
		sb.append(emailId);
		return sb.toString();
	}

}
