/*
 * Created on 2019-04-16 ( Date ISO 2019-04-16 - Time 01:30:06 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package com.Ecommerce.Repo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.Ecommerce.entity.OrderDetailsJpaRecord;



/**
 * Spring data Jpa repository for "OrderDetails" <br>
 */
@Repository
public interface OrderDetailsRepository extends JpaRepository<OrderDetailsJpaRecord, Integer>, JpaSpecificationExecutor<OrderDetailsJpaRecord> {
}